### ISSUE TITLE
Studenti, kteří se nepřihlásili na řádný termín obhajoby

### ISSUE THREAD

**Issue by nvbach91** [nvbach91/4IZ268-2018-2019-ZS#354]
@p31r 
@braj08 - příjde na opravný
@janf04 
@rinamoon - příjde na opravný
kopp05
hajd05
@BenesRadovan - příjde na opravný
@alex6krasnov 
@kudp02 - příjde na opravný
@pina01 
@dsejna - příjde na opravný

**Comment by braj08** [comment]
Mám v plánu se přihlásit na termín 25., protože ostatní byly už přes týden plný... je to tak v pohodě?
