### ISSUE TITLE
braj08

### ISSUE THREAD

**Issue by nvbach91** [nvbach91/4IZ268-2018-2019-ZS#363]
@braj08 prosím o doladění prvního projektu, nejdéle do 30.1.2019 12:00, jinak to bude za 4.

> Vážení studenti,
> 
> posílám info k první semestrální práci. 
> 
> První verzi práce musíte odevzdat do Neděle 04.11.2018 přes Git. Pak je týden času na doladění práce dle připomínek na GitHubu. Pak následuje bodování. Bodování proběhne pouze za předpokladu, že vaše stránky budou dostupné z internetu, tj. vaše Pull Requesty byly approved a merged. 
> 
> Na bodování se aplikují následující kritéria - https://goo.gl/Chkoko. Berte to jako checklist a měli byste všechna kritéria zohlednit ještě před odezvdáním projektu.

**Comment by braj08** [comment]
Ano, pracuju na tom... pak mám udělat nový pull request, je tomu tak?

**Comment by nvbach91** [comment]
ano
